// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"github.com/fastworkco/go-boilerplate/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthClient creates a new instance of MockAuthClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthClient {
	mock := &MockAuthClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthClient is an autogenerated mock type for the AuthClient type
type MockAuthClient struct {
	mock.Mock
}

type MockAuthClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthClient) EXPECT() *MockAuthClient_Expecter {
	return &MockAuthClient_Expecter{mock: &_m.Mock}
}

// GetTokenInfo provides a mock function for the type MockAuthClient
func (_mock *MockAuthClient) GetTokenInfo(token string) (domain.AuthTokenData, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenInfo")
	}

	var r0 domain.AuthTokenData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.AuthTokenData, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.AuthTokenData); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.AuthTokenData)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthClient_GetTokenInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenInfo'
type MockAuthClient_GetTokenInfo_Call struct {
	*mock.Call
}

// GetTokenInfo is a helper method to define mock.On call
//   - token string
func (_e *MockAuthClient_Expecter) GetTokenInfo(token interface{}) *MockAuthClient_GetTokenInfo_Call {
	return &MockAuthClient_GetTokenInfo_Call{Call: _e.mock.On("GetTokenInfo", token)}
}

func (_c *MockAuthClient_GetTokenInfo_Call) Run(run func(token string)) *MockAuthClient_GetTokenInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthClient_GetTokenInfo_Call) Return(authTokenData domain.AuthTokenData, err error) *MockAuthClient_GetTokenInfo_Call {
	_c.Call.Return(authTokenData, err)
	return _c
}

func (_c *MockAuthClient_GetTokenInfo_Call) RunAndReturn(run func(token string) (domain.AuthTokenData, error)) *MockAuthClient_GetTokenInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthService creates a new instance of MockAuthService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthService {
	mock := &MockAuthService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthService is an autogenerated mock type for the AuthService type
type MockAuthService struct {
	mock.Mock
}

type MockAuthService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthService) EXPECT() *MockAuthService_Expecter {
	return &MockAuthService_Expecter{mock: &_m.Mock}
}

// GetTokenInfo provides a mock function for the type MockAuthService
func (_mock *MockAuthService) GetTokenInfo(token string) (domain.AuthTokenData, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenInfo")
	}

	var r0 domain.AuthTokenData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.AuthTokenData, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.AuthTokenData); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.AuthTokenData)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthService_GetTokenInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenInfo'
type MockAuthService_GetTokenInfo_Call struct {
	*mock.Call
}

// GetTokenInfo is a helper method to define mock.On call
//   - token string
func (_e *MockAuthService_Expecter) GetTokenInfo(token interface{}) *MockAuthService_GetTokenInfo_Call {
	return &MockAuthService_GetTokenInfo_Call{Call: _e.mock.On("GetTokenInfo", token)}
}

func (_c *MockAuthService_GetTokenInfo_Call) Run(run func(token string)) *MockAuthService_GetTokenInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthService_GetTokenInfo_Call) Return(authTokenData domain.AuthTokenData, err error) *MockAuthService_GetTokenInfo_Call {
	_c.Call.Return(authTokenData, err)
	return _c
}

func (_c *MockAuthService_GetTokenInfo_Call) RunAndReturn(run func(token string) (domain.AuthTokenData, error)) *MockAuthService_GetTokenInfo_Call {
	_c.Call.Return(run)
	return _c
}
