// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	"github.com/fastworkco/go-boilerplate/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAuthProvider creates a new instance of MockAuthProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthProvider {
	mock := &MockAuthProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthProvider is an autogenerated mock type for the AuthProvider type
type MockAuthProvider struct {
	mock.Mock
}

type MockAuthProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthProvider) EXPECT() *MockAuthProvider_Expecter {
	return &MockAuthProvider_Expecter{mock: &_m.Mock}
}

// GetTokenInfo provides a mock function for the type MockAuthProvider
func (_mock *MockAuthProvider) GetTokenInfo(token string) (domain.AuthTokenData, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenInfo")
	}

	var r0 domain.AuthTokenData
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (domain.AuthTokenData, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) domain.AuthTokenData); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Get(0).(domain.AuthTokenData)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthProvider_GetTokenInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenInfo'
type MockAuthProvider_GetTokenInfo_Call struct {
	*mock.Call
}

// GetTokenInfo is a helper method to define mock.On call
//   - token string
func (_e *MockAuthProvider_Expecter) GetTokenInfo(token interface{}) *MockAuthProvider_GetTokenInfo_Call {
	return &MockAuthProvider_GetTokenInfo_Call{Call: _e.mock.On("GetTokenInfo", token)}
}

func (_c *MockAuthProvider_GetTokenInfo_Call) Run(run func(token string)) *MockAuthProvider_GetTokenInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAuthProvider_GetTokenInfo_Call) Return(authTokenData domain.AuthTokenData, err error) *MockAuthProvider_GetTokenInfo_Call {
	_c.Call.Return(authTokenData, err)
	return _c
}

func (_c *MockAuthProvider_GetTokenInfo_Call) RunAndReturn(run func(token string) (domain.AuthTokenData, error)) *MockAuthProvider_GetTokenInfo_Call {
	_c.Call.Return(run)
	return _c
}
